### ISSUE TITLE
Tempest Page text.

### ISSUE THREAD

**Issue by MartinHeZ** [jmoskie/maptool#1]
https://www.syncrpg.com/tempest/
1. "This page will serve front page and primary reference for the campaign setting and the various people, cultures and places within." should read "This page will serve **as the** front page and primary reference for the campaign setting and the various people, cultures and places within."
2. "The content is still in development, but we are working on it constantly and it will be made available when SyncRPG goes public." As far as I'm aware it is public now, so might be an idea to reword this.

**Comment by jmoskie** [comment]
Done, thanks!
