### ISSUE TITLE
Flurry Attacks

### ISSUE THREAD

**Issue by MartinHeZ** [jmoskie/maptool#15]
On the character sheet (V5.0) if you try to add a Flurry Attack to your weapons it will only work as a monk as it pulls stats from the "Monk Class Level" which means any Brawlers can't use it on the character sheet although they have an effective monk level equal to their brawler level.

**Comment by jmoskie** [comment]
This will be fixed in the new version of the sheet, to be released on Tuesday.

As we discussed, I already fixed it on your Brawler's sheet.
