### ISSUE TITLE
Modules Page

### ISSUE THREAD

**Issue by MartinHeZ** [jmoskie/maptool#2]
https://www.syncrpg.com/tempest/modules/

1."Captured by Adventure is a free an introductory adventure module..." should read "Captured by Adventure is a free introductory adventure module..." (removed the "an" before "introductory")
1. The "Captured by Adventure" text body and title appear to be too close to the image, a bit more spacing should make it look better. This is probably my own personal preference and should probably be disregarded :P 

3."The Rescue of Doniert Ironvale is a wilderness adventure module for 4th level PFRPG characters that is designed to for both new and experienced GMs and players to take advantage of the digital tools provided by SyncRPG." should read "The Rescue of Doniert Ironvale is a wilderness adventure module for 4th level PFRPG characters that is designed for both new and experienced GMs and players to take advantage of the digital tools provided by SyncRPG." (removed the "to" before "for both")
1. and 3. also occur on their respective module pages.

**Comment by jmoskie** [comment]
Got 'em all! Thanks!
