### ISSUE TITLE
Escape from Fort Nurovd page

### ISSUE THREAD

**Issue by MartinHeZ** [jmoskie/maptool#4]
https://www.syncrpg.com/tempest/oneshots/nurovd/
1. "You may surrendered, or perhaps you stood against them, but it matters not: You were captured with the rest as slaves." should read "You may **have** surrendered..."
2. "Dominate workcamps throughout Shigai, Gnomeria and Stormseye are filled with slaves from all corners of the World." should read "**Dominant** workcamps throughout Shigai, Gnomeria and Stormseye..."

**Comment by jmoskie** [comment]
Fixed number 1, but number 2 is intentional! The evil empire of hobgoblins and devils is known as "The Internal Dominate of Chax."
